# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
# orbs:
#   aws-cli: circleci/aws-cli@0.1.21
jobs:
  lambda_check:
    # executor: aws-cli/default
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Install AWSCLI
          command : |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Zip Artifact
          command: |
            zip index.zip index.js
      - run:
          name: Upload LambdaFunction to S3
          command: |
            aws s3 cp index.zip s3://${bucket_name}/index.zip
      - run: 
          name: Install less
          command: |
            sudo apt-get install less -y

      - run:
          name: Update lambdaFunction code
          command: |
            aws lambda update-function-code --function-name EmailService --s3-bucket ${bucket_name},bundleType=zip,key=index.zip --region us-east-1
      
workflows:
  version: 2
  lambda:
    jobs:
      - lambda_check